<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="javascript"
    nsURI="http://www.brainspeedtech.com/constraint/software/web/javascript" nsPrefix="javascript">
  <eClassifiers xsi:type="ecore:EClass" name="JavascriptGeneration" eSuperTypes="platform:/plugin/com.brainspeedtech.swarm.layer/model/layer.ecore#//NatureBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="JavascriptGeneration"/>
      <details key="kind" value="empty"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
