<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="html"
    nsURI="http://www.brainspeedtech.com/constraint/web/html" nsPrefix="html">
  <eClassifiers xsi:type="ecore:EClass" name="HtmlGeneration" eSuperTypes="platform:/plugin/com.brainspeedtech.swarm.layer/model/layer.ecore#//NatureBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="HtmlGeneration"/>
      <details key="kind" value="empty"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexPage" eSuperTypes="platform:/plugin/com.brainspeedtech.swarm.layer/model/layer.ecore#//ConstraintBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="IndexPage"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" lowerBound="1"
        eType="ecore:EClass platform:/plugin/com.brainspeedtech.swarm.inst/model/inst.ecore#//CellInstance">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="instance"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
